branches:
  only:
    - source
language: ruby
rvm:
  - 1.9.3
before_script: 
  # Set the git config stuff, so Git stops yelling at us
  - git config --global user.name "Ahmet Demir (Travis-CI)"
  - git config --global user.email "me@ahmet2mir.eu"
  # Set read-write git origin
  - git remote set-url origin $REPO.git
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set deployment target to github pages
  - bundle exec rake setup_github_pages[$REPO]
  # To reset the 'url' to the custom domain in '_config.yml'
  - git checkout -- _config.yml
script:
  # Generate site
  - bundle exec rake generate
after_script:
  # Deploy!
  - bundle exec rake deploy
env:
  global:
    # Repo read-write address
    - REPO="git@github.com:uptoelevenfr/uptoelevenfr.github.io"
    # SSH key. Encoded. See https://gist.github.com/4631240
    - secure: "eDfov7NVdyok3OPJ+XVt8PH0ydWXkYLv8mU7u0W5RjJYGJxNWhpPMEv4q6VSuyIeXdqPH+AF9D5TyARyO0R2caYwit4bqmfoQltuKIq3sHmjq7yNVp3gUxkeSUSn/FBKuZM0PqdYmHbVzN/3WOKE+0pf8G6GicmQwf35QfbKr5M="
    - secure: "4sqFabjK5spm6jkXhlHpwS9kHE8fUxWJcSJ817ncMxJX9fwu8Tq7u4Zxc0Ow/iKOxMgBK5tybz0PZxB6oo7YPc9Ug8mz1boyD+yKDxUcuUuta6ltaAEOY1K3vdTSD+T0Yr7M+Xhe277bsV9hCpfXC42d51xB27dHigPL/rdDRgU="
    - secure: "TGzAgjV/jDLa1korHuTA8V3lOj/HIYhN9/8BTCDs8rarGrre02DegbRexuCtJM/pqg8VNJwcp+gtOqkZ2BB3SGaqu0dt2R3LoHFQlMmkT5lCic5oBUnS5pFGayEaQezTD7AaKVQl0//puGWNIdOZBbPJmRV9KKEJKxZzibugozk="
    - secure: "tMfNJ6aR/OJjU1/Z8U/ZnG96nAOPJnAkJMTjagBVEHUlQyRWMDQ6f76d4wRR52CMqNJ9Fb5eh/hEhxOcM3hQsMYUWkfI37pywoH02GKS9mQVN0QtReBIgirEK7+njswxhhiHOo2d/j2prL/kZqQ33rB6uhFOwnqFQ5kTG54Btcs="
    - secure: "scICAQM8VuplU1+O2hpOp+fHNgYzbnQSSgmSFqN24bOekZvopdT0dfCShcwCY6vOIh4O3D5BAXfXe2AF18cMPOyAwytfANSvfblNBZ7AKaXRH7GTaKD+KpWB3howpnA9HbOjkxyaoIIwCIjRS5XeGBCqBqLls5U13tnbJ0rWZGs="
    - secure: "tUleC1xZSdL3CKBfP7csmRLJ+JAN0Z/ag7VhHLfoBZncjYOI9BqVpiiU/QnpeRK64WzkPQqdrY+dyD3ShQkovSPJ0eDonv2118tuNW7+o7oZZYJHJJQhTiaVTK2eBCvTmCqt1hfJCozPtGpwVWHUz5nfzjmvEmyo890olql4Dtc="
    - secure: "0LRsRfOMFxuXwN/ZQPPgRhTUC6Ukagv3ITcJJHnKeAD0fgKwkqfzDUvsybWM6vDBKw2nLyX9iPOaCI8OrUU4tzcWfgujPk4LTcWY2TE2zUt90qVXjzurNACVjytqdocw2/E0ey0BQflVBVZeGPWql3eHdAGyOHF27wn5fW6BnPI="
    - secure: "hm21l7v1Hl6Vt3QfLXgthYBZH1gD1zwCX5VD9M/m6jEyuMmpSgW/l59/NsSZu+qV4fs5+wnMkbkCIg3DT0ese+mNp/6SbWbvSqzPkbaimdy2H8hIiQJjY36vJZEL4dzotMusZphjEaENT7G6pipo1ijaFWGT/yj7yVt3NNbKToo="
    - secure: "31S5XZ1QLlkO5+rGC/XqmwBpnbK+AxSj/EDTbsEys7wM7XqDWqeWRQ/bKGazPEH5Q3VSyQB4Sb1WOa+NGwcHwfGmXG1pRdlsDhR21lZxFMhkObGA8hy1JgcMVzFodS7LXRokNP7lb35SQHBinAXOKzkUZFoTJ+BRp3AeKooRvPI="
    - secure: "odengPQb+MEYCkB3Fhtba57hiIrGDy+7ofiui8iAHFHuh2i277YuD/Vmdi1H/+ThWnFe56r1bGwX/M628ImwLuGDI7/5Zj0Lv5dLPgDFUBJbHyL4gJQ3xpN9uwL/DB1GNYQQHSx8mGz7OlcDNjQE/1BUEMB3iVC4hRVzfamjZVo="
    - secure: "sV79rjdIFmA22Y0CYSQ6t82NhhHneOvPREqdO4ZmRTjKESnptYIdhPwnNeITszw0tKD3DxqxRTo1I25xmTcv6xUQmr6QIzFzr/oammRUuDkTIKRSdh7upnBAgOMNVf1sE/D2ApISJ6zr6IJyiJfJopn5dRpBMFK6E4ES6nDu8Wg="
    - secure: "nfBkYrpQ725CMgVnJJpqcbSdQAeDNqqLwCxCBBOPqQr7Omr8qD0wUHuK11mREPtbrmRf8WYBpnB8qifhQePI9iCCbS7hYyRF37siYeCgtkDh2lynieT/GA9KtlxQYeZO4bE/recL+NDWACi30dkWrS7SEssVvjaGS81xa1WsrJw="
    - secure: "1K0PvsG8iVOkWnOoK03PL43G+d6rwnRQnhCR4hSbxby8cIXAOae3rNmCTAZ+V5o8B8zgPiJH6zhE1ezzFXFXqO5PiSO6Z8/nRTzIEs1UQBnw9Gi/BYHUDnydJpGzM9pBt3jJlVjEOQGU3WmhyRJmPkkNdFlJS/ZUJoK69tZwHTU="
    - secure: "Lw72fQkbDQpPG+pGP9IPUJ9hdiFZjMblvi9+SLbt6DxVBfKpD8OchrLZhNAXSitY0DMPDsWWA6JXLQV4MwuJgSDeOH4JTLx1b9JpmEmlpX52SQZqsHbqfTkVMMhtfVVCQ6TKP15oGdX0QEaQLiE8ckH9yvc1em7ohjFm33Dme+o="
    - secure: "zAQHqMct0s5T9aEdY+KiixiRA42cfjtNLUsncTO0oXswvqObxO2EIMHtaiGDH98u4zGMsBGzo3J5sQdfKKXm1z32GVGyV76tPTXZWpNBLfhG/ZBh16SKP/fIjISlgQWhxKdDVboQ4U4IdtmHaITBfbEmcuhbjAr0pIjYG9p4rek="
    - secure: "4RqhBbWZexw6J0HJVzNI0XaU0TtK6DyyfLBuUlE7A35iDF5FfBab6V32zs6B+hgPNZLzTP1RNeznpafTAApuuJu0K+8zoGDyz884ej4u5v+aMCQrnz91wHAAtvj6NSEaZD5n9GKFNLayAW6RUIDCMgtS6iyv7kbLUyuyjhlpPu0="
    - secure: "k+/UOEm09sPdT9DLuB4305EPsOSeosKc0DCmClkrpx++FFXbejSHr23K/eeAClg3zKmX2y79S4kKeDPC95dwF+quUMaSxhHLAzn2Gm7TNSbvfCcQGPi2NcZwr75+j7eI/QfzUuIsPt0wgarowftV7myA6X8KqP6dSX7oueMO3qk="
    - secure: "3zGZPmgpZWyEvFYlKGP4/tWWBFIYYwLaW6CmWDNrLWM95IyTvnZ5Plx+mox/mbcIildz53qpk8Z5/bA/7Wxpmk9TFzME4c/08/s2BlcwPwhMd6lCHabTNW/cYprhXicdrJGRLHGEYKMXBd4A/5he2WSRZlI+aPpkMSWC6DuSnSA="
    - secure: "SuQurTgSmiKuyHcoTRXUN5B1zPgqsSa6YdZ80MGg6WUN2pxrD5XMIc8hHPj5cNazqQcRIwlpXsXcDovV+dWTXMuX4v9pxYtHUYBVPHFHslJUk/P9sy9WkL4WGX3NjAt9othz/1xoGS83k53/oXs0ey0VOBsLuaCUE0BDn+/oEgk="
    - secure: "ipz4lj1OLg+5Tlj9VjdR1QsAEEsW8PNmP3EuWEca0sLU/Xi5rqr/tVllDD3lxhHzw3qBpzup5aN0pHJUBuToaAt54ZctYZVth2ScLonkwow+cIhYKJ/e8KTZXyuWuCuRKat0ZIXCHaLpJpMz8A2QebMDroSpfkBLt5fQhcIDPcQ="
    - secure: "Nld/FrsJUgYLqpVJe2nbFB/QwHkUNwH98Jf/zMAF1yVFgmz7kIKD5bf7w0q3eOnhl6UgoYL+WrXPVUSBId9e/n8A2dXAsUMPwLfSUEhK8zC84HIslnd05EYV8bMPKn8NANiVBJrgUQTCv8Xay30NZ4lv4IyPuyvFZkl6sqkmi8o="
    - secure: "3QDb5s5V3WhwYI0iexlwR1rlPSmutVwmR6Gl8U1nykIWS/TqS8KTh1sXCY9gh2eVh4+Xbh6m+BkOKkGbPFHPw3uzzXKLPgd19ClFCVaiTt7tSBxNKJg0oT34EgZ+8bLdXVWVrERWdd41z8ZibOqGn+EfI4niZ0d9y//k90xZOgU="
    - secure: "F+y+48CFqdj+oGoa76GV2xt678TZQWgCHkf5iek7tZogWJAOWjP2il0gDve5uqygr4XQ24MufPsQEJOtFObLIDmB228gQ/+5tNQoBf7YuxdQhH8r8HM98WiVVH6Q4N9ilnGH3rjax+Y757JAGu4p/XKGD+h3vD9sFEW+FPrEAf8="
    